import { Link } from "react-router-dom";
import { useLanguage } from "../i18n/LanguageContext";

const content = {
  en: { label: "About", title: "There is a world full of noise. We want to make room for something deeper.", intro: "The Small Voice is a digital platform created to help people begin and grow in a genuine relationship with God through storytelling, teaching, digital media, and practical resources.", first: "We believe a person's journey with God does not always begin in a church building or with a perfect understanding of faith. Sometimes it begins with a story, a question, a moment of doubt, a testimony, or a quiet realization that there must be something more.", emphasis: "The Small Voice exists for that moment.", second: "We tell stories that make people think, feel, question, hope, and look toward God. We share testimonies of real people, explore questions about faith and life, provide learning resources, and create digital experiences that help people take their next step.", vision: "Our vision", visionText: "To see people everywhere awakened to God, growing in genuine faith, and becoming equipped to help others do the same.", mission: "Our mission", missionTitle: "Make spiritual growth accessible to anyone, anywhere.", missionText: "We use storytelling, teaching, digital tools, and digital media to help people take their next step.", create: "What we create", createTitle: "Many ways to take one honest step.", closing: "We don't believe people need more noise. They need truth they can encounter, stories they can recognize themselves in, people they can walk with, and opportunities to take one honest step at a time.", action: "Join the conversation", steps: ["Discover", "Story", "Learn", "Grow", "Connect", "Serve", "Help others"], creations: [["Stories", "Real stories, testimonies, reflections, and experiences that explore faith, life, people, and the world around us."], ["Teaching", "Practical and thoughtful content that helps people understand God, faith, Scripture, and the questions that matter."], ["Resources", "Books, videos, guides, courses, and other materials designed to help people continue exploring and growing."], ["Digital tools", "Technology that can make spiritual practices and growth more accessible, practical, and personal."]] },
  sw: { label: "Kuhusu", title: "Kuna kelele nyingi duniani. Tunataka kutengeneza nafasi kwa kitu cha kina zaidi.", intro: "The Small Voice ni jukwaa la kidijitali lililoundwa kuwasaidia watu kuanza na kukua katika uhusiano wa kweli na Mungu kupitia hadithi, mafundisho, vyombo vya habari vya kidijitali na rasilimali za vitendo.", first: "Tunaamini safari ya mtu na Mungu haianzi kila mara katika jengo la kanisa au kwa ufahamu mkamilifu wa imani. Wakati mwingine inaanza kwa hadithi, swali, wakati wa shaka, ushuhuda, au utambuzi wa utulivu kwamba lazima kuna kitu zaidi.", emphasis: "The Small Voice ipo kwa ajili ya wakati huo.", second: "Tunasimulia hadithi zinazowafanya watu kufikiri, kuhisi, kuhoji, kutumaini na kumwelekea Mungu. Tunashiriki shuhuda za watu halisi, tunachunguza maswali kuhusu imani na maisha, tunatoa rasilimali za kujifunza, na tunaunda uzoefu wa kidijitali unaowasaidia watu kuchukua hatua inayofuata.", vision: "Maono yetu", visionText: "Kuwaona watu kila mahali wakiamshwa kwa Mungu, wakikua katika imani ya kweli, na kuwezeshwa kuwasaidia wengine kufanya vivyo hivyo.", mission: "Dhamira yetu", missionTitle: "Kufanya ukuaji wa kiroho upatikane kwa kila mtu, kila mahali.", missionText: "Tunatumia hadithi, mafundisho, zana za kidijitali na vyombo vya habari vya kidijitali kuwasaidia watu kuchukua hatua inayofuata.", create: "Tunachounda", createTitle: "Njia nyingi za kuchukua hatua moja ya kweli.", closing: "Hatuamini watu wanahitaji kelele zaidi. Wanahitaji ukweli wanaoweza kukutana nao, hadithi wanazoweza kujitambua ndani yake, watu wanaoweza kutembea nao, na fursa za kuchukua hatua moja ya kweli kwa wakati.", action: "Jiunge na mazungumzo", steps: ["Gundua", "Hadithi", "Jifunze", "Kua", "Ungana", "Hudumia", "Saidia wengine"], creations: [["Hadithi", "Hadithi halisi, shuhuda, tafakari na uzoefu unaochunguza imani, maisha, watu na ulimwengu unaotuzunguka."], ["Mafundisho", "Maudhui ya vitendo na ya kina yanayowasaidia watu kumwelewa Mungu, imani, Maandiko na maswali muhimu."], ["Rasilimali", "Vitabu, video, miongozo, kozi na vifaa vingine vilivyoundwa kuwasaidia watu kuendelea kuchunguza na kukua."], ["Zana za kidijitali", "Teknolojia inayoweza kufanya mazoea ya kiroho na ukuaji kupatikana zaidi, kuwa wa vitendo na wa binafsi."]] },
};

export default function About() {
  const { language } = useLanguage();
  const copy = content[language];
  return <main className="container page mission-page"><header className="mission-hero"><p className="eyebrow">{copy.label}</p><h1>{copy.title}</h1><p>{copy.intro}</p></header><section className="mission-prose"><p>{copy.first}</p><p><strong>{copy.emphasis}</strong></p><p>{copy.second}</p></section><section className="mission-statement"><p className="eyebrow">{copy.vision}</p><blockquote>{copy.visionText}</blockquote></section><section className="mission-split"><div><p className="eyebrow">{copy.mission}</p><h2>{copy.missionTitle}</h2><p>{copy.missionText}</p></div><ol className="journey-path">{copy.steps.map((step, index) => <li key={step}><span>{String(index + 1).padStart(2, "0")}</span>{step}</li>)}</ol></section><section className="mission-creates"><div className="section-heading"><div><p className="eyebrow">{copy.create}</p><h2>{copy.createTitle}</h2></div></div><div className="mission-create-grid">{copy.creations.map(([title, description]) => <article key={title}><h3>{title}</h3><p>{description}</p></article>)}</div></section><section className="mission-closing"><p>{copy.closing}</p><Link to="/contact" className="button">{copy.action}</Link></section></main>;
}
