import { useLanguage } from "../i18n/LanguageContext";

const content = {
  en: { label: "Give", title: "Help the voice travel further.", intro: "The Small Voice exists so that people can discover God, explore faith, and grow spiritually, wherever they are.", description: "Creating meaningful content, producing digital media, building useful tools, and reaching people takes people, technology, time, and resources. Your giving helps make that work possible.", help: "Your generosity can help us", impact: "Every contribution matters", impactTitle: "One small act can start a longer journey.", impactText: "You don't have to change the whole world at once. Sometimes you help one person discover a story, and that story becomes a step toward something new.", give: "Give", choice: "Choose the way you would like to support the work.", once: "Give once", monthly: "Give monthly", steps: ["Your gift", "Content", "Discovery", "Learning", "Growth", "Transformation", "Another life"], outcomes: [["Create stories", "Support writers, storytellers, photographers, filmmakers, and creators who produce meaningful content."], ["Create learning resources", "Develop accessible guides, courses, videos, and other resources for people exploring faith and seeking to grow."], ["Build digital tools", "Develop technology that helps people practice, learn, reflect, connect, and grow."], ["Reach more people", "Help distribute content digitally so that someone searching for answers can encounter something meaningful at exactly the right moment."], ["Equip contributors", "Help create opportunities for people with a story, skill, or calling to contribute to the mission."]] },
  sw: { label: "Toa", title: "Saidia sauti ifike mbali zaidi.", intro: "The Small Voice ipo ili watu waweze kumgundua Mungu, kuchunguza imani, na kukua kiroho, popote walipo.", description: "Kuunda maudhui yenye maana, kutengeneza vyombo vya habari vya kidijitali, kujenga zana muhimu, na kuwafikia watu kunahitaji watu, teknolojia, muda na rasilimali. Mchango wako husaidia kufanya kazi hiyo iwezekane.", help: "Ukarimu wako unaweza kutusaidia", impact: "Kila mchango una maana", impactTitle: "Tendo moja dogo linaweza kuanza safari ndefu.", impactText: "Huhitaji kubadilisha dunia nzima kwa wakati mmoja. Wakati mwingine unamsaidia mtu mmoja kugundua hadithi, na hadithi hiyo inakuwa hatua kuelekea kitu kipya.", give: "Toa", choice: "Chagua namna unavyotaka kuunga mkono kazi hii.", once: "Toa mara moja", monthly: "Toa kila mwezi", steps: ["Zawadi yako", "Maudhui", "Ugunduzi", "Kujifunza", "Ukuaji", "Mabadiliko", "Maisha mengine"], outcomes: [["Kuunda hadithi", "Kusaidia waandishi, wasimuliaji wa hadithi, wapiga picha, watengenezaji wa filamu na wabunifu wanaotengeneza maudhui yenye maana."], ["Kuunda rasilimali za kujifunza", "Kuendeleza miongozo, kozi, video na rasilimali nyingine zinazopatikana kwa watu wanaochunguza imani na kutafuta kukua."], ["Kujenga zana za kidijitali", "Kuendeleza teknolojia inayowasaidia watu kufanya mazoezi, kujifunza, kutafakari, kuungana na kukua."], ["Kuwafikia watu wengi", "Kusaidia kusambaza maudhui kidijitali ili mtu anayetafuta majibu aweze kukutana na kitu chenye maana kwa wakati unaofaa."], ["Kuwawezesha wachangiaji", "Kusaidia kutengeneza fursa kwa watu wenye hadithi, ujuzi au wito wa kuchangia dhamira hii."]] },
};

export default function Give() {
  const { language } = useLanguage();
  const copy = content[language];
  return <main className="container page give-page"><header className="mission-hero"><p className="eyebrow">{copy.label}</p><h1>{copy.title}</h1><p>{copy.intro}</p></header><section className="give-intro"><p>{copy.description}</p></section><section className="mission-creates"><p className="eyebrow">{copy.help}</p><div className="mission-create-grid">{copy.outcomes.map(([title, description]) => <article key={title}><h3>{title}</h3><p>{description}</p></article>)}</div></section><section className="give-impact"><div><p className="eyebrow">{copy.impact}</p><h2>{copy.impactTitle}</h2><p>{copy.impactText}</p></div><ol className="journey-path">{copy.steps.map((step, index) => <li key={step}><span>{String(index + 1).padStart(2, "0")}</span>{step}</li>)}</ol></section><section className="give-actions"><h2>{copy.give}</h2><p>{copy.choice}</p><div className="hero-actions"><a className="button" href={`mailto:hello@thesmallvoice.org?subject=${encodeURIComponent(copy.once)}`}>{copy.once}</a><a className="button secondary" href={`mailto:hello@thesmallvoice.org?subject=${encodeURIComponent(copy.monthly)}`}>{copy.monthly}</a></div></section></main>;
}
